### ISSUE TITLE
Example be broken

### ISSUE THREAD

**Issue by heatherbooker** [kingofthestack/react-chat-window#109]
In the readme:
```
import React, {Component} from 'react'
import {render} from 'react-dom'
import {Launcher} from '../../src'

class Demo extends Component {

  constructor() {
    super();
    this.state = {
      messageList: messageHistory
    };
  }
```
`messageHistory` is undefined >> - could be confusing for new users.

**Comment by heatherbooker** [comment]
Also, `import {Launcher} from '../../src'` is a good path for the actual demo code but makes less sense as a readme example ><

**Comment by heatherbooker** [comment]
Also, `render` don't need to be imported.

**Comment by dharness** [comment]
LOL these guys are a mess
