### ISSUE TITLE
Remove sound on incoming message 

### ISSUE THREAD

**Issue by Yodetoo** [kingofthestack/react-chat-window#110]
Add a feature to remove sound by passing a props

**Comment by heatherbooker** [comment]
@Yodetoo Sounds doable! It should be simple - are you interested in implementing it or do you just want to use it?

(Related: @dharness there are 3 `.mp3`s but only the notification one seems to be used - any plans to use the others?)

**Comment by dharness** [comment]
Nah - if someone does this task it'd be nice to also remove unused mp3s

**Comment by Yodetoo** [comment]
thank you very much, this will help a lot <3
