### ISSUE TITLE
Add build step/instructions to update emojis

### ISSUE THREAD

**Issue by heatherbooker** [kingofthestack/react-chat-window#123]
We seem to have a static file of emojis, where did they come from? Where did they go? (where did they come from, cotton eyed joe?) In `emojiData.js` (soon to be `emojiData.json`).

It would be nice to document somehow so when new emojis are introduced we can easily update.

**Comment by dharness** [comment]
Yeah the emojis is one of the most annoying parts - it would be better if there was some kind of browser api for getting emojis, rather than having them as text. This file also takes time to load and download that I'd prefer to avoid. I don't remember where I even got this.

**Comment by heatherbooker** [comment]
Ok, well, I guess we'll deal with it when the time comes to update the emoji list. 😂
