### ISSUE TITLE
How can i import into a plain html file?

### ISSUE THREAD

**Issue by juzejunior** [kingofthestack/react-chat-window#142]
Recently i need it to import this component into a non react project, like a simple html page, how can i do this? It's possible? I've been tryin' to import UMD file generated, but it does not work.

**Comment by NaumanMoazzam** [comment]
If you want to add into simple HTML page;

1. Clone this project.
2. Run npm install/ yarn then npm start/ yarn start
3. After successful start, run npm build. This will create a build folder with CSS & JS folder.
4. Copy these files into your HTML page, and add a div with ID anywhere in the code, for example: 
           <div id="root"></div>
And import all the CSS & JS.
5. This will add chat widget into your simple HTML page.

**Comment by heatherbooker** [comment]
Hi @juzejunior, I don't think you can actually use a react component in a non-react project, sorry - you will have to look for plain javascript solutions or perhaps find a jquery based library to rely on. Good luck!
