### ISSUE TITLE
send button not rendering

### ISSUE THREAD

**Issue by gravitymedianet** [kingofthestack/react-chat-window#144]
In the UserInput component, it appears the send button has been left out. It is not rendering when I put the ChatWindow in my app.

See line 147:

``
          <div className="sc-user-input--button"></div>
``

EDIT TO ABOVE --

It appears the send button replaces the files icon when you type.

Can you make it so that the send can be its own icon? We dont want users for example to upload file.

**Comment by dharness** [comment]
Sorry, we are no longer working on this project.
