### ISSUE TITLE
Can't load notification.mp3 file

### ISSUE THREAD

**Issue by LeThanhTung17** [kingofthestack/react-chat-window#145]
error  in ./node_modules/react-chat-window/es/assets/sounds/notification.mp3

Module parse failed: Unexpected character '' (1:3)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)

 @ ./node_modules/react-chat-window/es/components/Launcher.js 11:0-71 42:26-46
 @ ./node_modules/react-chat-window/es/index.js

**Comment by dharness** [comment]
@LeThanhTung17 please provide more information when opening an issue, what system you're on, what your setup is, what you've tried etc.

**Comment by LeThanhTung17** [comment]
@dharness thanks your replied, I fixed that error, just add .mp3 to the webpack.config file

**Comment by LeThanhTung17** [comment]
> @LeThanhTung17 please provide more information when opening an issue, what system you're on, what your setup is, what you've tried etc.

@dharness thanks your replied, I fixed that error, just add .mp3 to the webpack.config file

**Comment by quannguyennn** [comment]
@LeThanhTung17  im using Next and resolve this by adding mp3 to webpack but another issue is it can't load global css from node_modules. Help

**Comment by LeThanhTung17** [comment]
please show me some photos in your webpack and your  issue

Vào Th 5, 28 thg 5, 2020 vào lúc 14:47 quannguyennn <
notifications@github.com> đã viết:

**Comment by LeThanhTung17** [comment]
> @LeThanhTung17 im using Next and resolve this by adding mp3 to webpack but another issue is it can't load global css from node_modules. Help

please show me some photos in your webpack file where are you adding mp3 and adding css
