### ISSUE TITLE
sending multiline message doesn't work

### ISSUE THREAD

**Issue by nnur** [kingofthestack/react-chat-window#4]
https://puu.sh/wuou2/1aa22884f6.png

This will send as poopdoop

**Comment by heatherbooker** [comment]
Seems to be resolved, in ff I can send multiline messages, plz re-open if not! :+1:

**Comment by heatherbooker** [comment]
Scratch that, I misunderstood, this is indeed the case. Re-opening!

**Comment by heatherbooker** [comment]
#49 similar request. I think this is resolved (tested in the demo)! 🎉 

![image](https://user-images.githubusercontent.com/12223751/52885636-dc494200-313f-11e9-97db-43206c557350.png)
