### ISSUE TITLE
Unable to display svg image for chat icon

### ISSUE THREAD

**Issue by vkhattar** [kingofthestack/react-chat-window#48]
Unable to render the svg image for chat icon. When  I changed the image to a png image it worked properly, unfortunately I will not be able ship it with my changes.

Another suggestion here, just like how there is a slack image option for props, can we have something like that for this as well ? 

Any help will be appreciated. Thanks.

How image tag looks like with svg - 
`<img class="sc-closed-icon" src="/58a15de4005b6706fd064d5778a80c4e.svg">`

How image tag looks like with png - 
`<img class="sc-open-icon" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAfCAMAAACxiD++AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAtUExURUxpcf///////////////////////////////////////////////////////3EAnbYAAAAOdFJOUwADZ66SoQjEhnS7/gsNGQL7+wAAAKtJREFUKM+F01sOhCAQRNESFV/I/pc70Og0YJfyJbmHhBAbGGYHstw8IPV4EOGOmERYIhGpxyUAJxHSz/xlC+1FxE64qB1yj1ZID7oXsel+63ovnj2JXUXue+hvrcLugL+EdG+9XBG8X+Kl34J3YM1g/egvIvdx5EK691RIz78YEXdnQrst6m6JqemXmNo+D/WJNAyVePZWWL0WdlfB+l+UAQQReaAc65DB/wGsZgzLN0IQWAAAAABJRU5ErkJggg==">`

**Comment by vkhattar** [comment]
aah i see what you mean, I can probably work on it as well. But this one is the most important for me as I am unable to get the chat icon image to be rendered. Ill add an image to show you what i mean. 

<img width="348" alt="screenshot 2017-11-15 12 54 29" src="https://user-images.githubusercontent.com/1714264/32852151-1cb10876-ca05-11e7-9374-5a5edb88f0a9.png">

<img width="447" alt="screenshot 2017-11-15 12 59 21" src="https://user-images.githubusercontent.com/1714264/32852119-02f6b2f0-ca05-11e7-9c31-d940f475da34.png">

**Comment by heatherbooker** [comment]
I'm not sure if this is related to #68, but the SVG displays alright in the demo on github pages as well as locally for me on chrome/firefox/safari. If you can provide more information and/or a reproduction we'll be happy to re-investigate and try to help solve this - sorry we can't offer more help at this point! ><
