### ISSUE TITLE
Why is there a hover effect but no action on the team name?

### ISSUE THREAD

**Issue by heatherbooker** [kingofthestack/react-chat-window#84]
On Firefox (+ mabe others), there is a hover effect but no action on class="sc-header--team-name" - should we remove the effect or add an action such as optional link?

**Comment by dharness** [comment]
yea let's remove the hover effect

**Comment by heatherbooker** [comment]
@dharness Wouldn't it be nice if this issue was auto-closed now based on the linked PR being merged? :heart_eyes:

**Comment by dharness** [comment]
Sometimes an issue may be completed across multiple PRs though
