### ISSUE TITLE
Can't tell who sent files on mobile

### ISSUE THREAD

**Issue by heatherbooker** [kingofthestack/react-chat-window#85]
Should files have different outlines/shades/something to differentiate the user? 

Seems that files from either "us" or "them" appear the same and can only be differentiated by which side of the screen they are on; however, you can't use this when on mobile there is a very long filename, as it expands very wide.

Or maybe the solution is smaller max width.

**Comment by dharness** [comment]
@heatherbooker can you include some screenshots?

**Comment by heatherbooker** [comment]
Hm I can't repro on chrome using the small-screen emulator thing. We can re-open if it comes up again!
