### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by heatherbooker** [kingofthestack/react-chat-window#91]

**Comment by KBPsystem777** [comment]
agreed with @heatherbooker 👍

**Comment by harshgupta7** [comment]
I think most people would be wary of using it in production without this resolved @dharness

**Comment by KBPsystem777** [comment]
I think no one is maintaining this anymore?...

**Comment by dharness** [comment]
@KBPsystem777 Correct, this is not under active maintenance
